package me.dariansandru.domain.proof;

public enum Strategy {
    CONJUNCTION_STRATEGY,
    DISJUNCTION_STRATEGY,
    IMPLICATION_STRATEGY,
    EQUIVALENCE_STRATEGY,
    NEGATION_STRATEGY,
    PROOF_BY_CASES,
    NO_STRATEGY
}
